### ISSUE TITLE
问个问题……、提个问题？

### ISSUE THREAD

**Issue by zgdlime** [CNMan/XDHYDCD#1]
@CNMan
1、第三列：汉语拼音的“拼音”是用第三方软件制作的？还是纸质原版的？有出处吗？
2、这些“RECID=R2012111540000002”编号是什么意思？“知网”是什么？
3、这些字“𠉂”、“偌	ruò”、“诩	xǔ”行前有空格。
4、这些字“东(東)	dōng”、“储(儲)	chǔ”、“门(門)	mén”有繁体对应，其他没有？

**Comment by CNMan** [comment]
1.是爬知网的
2.[知网](http://gongjushu.cnki.net/)，那个编号其实没什么用，整理的时候顺便保留下来了
3.这些是我整理其他数据的时候发现知网漏掉的，前面是一个TAB，第一列数据是空的
4.知网只有这几个有，为保持一致，我已经删掉了

**Comment by zgdlime** [comment]
@CNMan 再提几个问题
#单字问题：
RECID=R2012111530048115	閕	xiǎ,又读xià（是","分开，不同于其他";"分开）
RECID=R2012111540021730	散	㪚sǎn（多了一个"㪚"字）

#词语问题：
RECID=R2012111540008286	维生素	wéi shēng sù B<#sub>1</sub#>
RECID=R2012111540008287	维生素B	wéi shēng sù B<#sub>2</sub#>
RECID=R2012111540008288	维生素B	wéi shēng sù B<#sub>6</sub#>
RECID=R2012111540008289	维生素B	wéi shēng sù B<#sub>12</sub#>

RECID=R2012111530001345	上色	①shàng sè;②★
RECID=R2012111530001784	丈夫	①zhàng fū;②zhàng★
RECID=R2012111530006041	直冲	①zhí chōng;②★
RECID=R2012111530006846	区处	①qū chǔ;②★
RECID=R2012111530009101	人家	①rén jiā;②rén★
RECID=R2012111530016810	农场	①nóng cháng;①nóng cháng★[①①]
RECID=R2012111530022368	云子	①yún zi;②★
RECID=R2012111530031928	花项	①huā xiàng★
RECID=R2012111530033545	落魄	①luò pò,又读luò tuò;②luò pò;③luò bó★[相同]
RECID=R2012111530036358	头头	①tóu tóu;②tóu★
RECID=R2012111530037070	小水	①xiǎo shuǐ;②xiǎo★
RECID=R2012111530040211	咕哝	①gū nong;★
RECID=R2012111530040213	咕唧	①gū jī;②gū★
RECID=R2012111530041139	哽哽	ǹg ǹg;又读ńń★[ń ń]
RECID=R2012111530042148	嘎巴	①gā bā;②★
RECID=R2012111530045318	犯难	①fàn nàn;②fàn★
RECID=R2012111530054278	灌肠	①guàn chang;②guàn★
RECID=R2012111530056020	情好	①qíng hào;②qíng★

**Comment by CNMan** [comment]
RECID=R2012111530048115 閕 xiǎ,又读xià（是","分开，不同于其他";"分开）
RECID=R2012111530033545 落魄 ①luò pò,又读luò tuò;②luò pò;③luò bó★[相同]

`,`同一义项读音不同；`;`不同义项读音不同

RECID=R2012111530031928 花项 ①huā xiàng★
RECID=R2012111530040211 咕哝 ①gū nong;★

这两个原书如此，可能是编者忘记增加义项和注音了

其他的已修正

**Comment by zgdlime** [comment]
@CNMan 还有：
0035	RECID=R2012111530001022	三K党	sān（音）
1761	RECID=R2012111540002010	透物电光	tòu wù diàn guāng X（没有X音）

**Comment by CNMan** [comment]
@zgdlime 多谢，已修正更新
